# CSE213 - Numerical Analysis

# LAB 0 - An Introduction to Numpy and Matplotlib

## Contents

1. What is Numpy?
2. Creating Numpy arrays
    * From Python lists
    * Using `arange` and `linspace`
    * Using special functions
3. Indexing and Slicing
4. Creating 2-D matrices
5. Indexing and Slicing (again)
6. Basic operations
7. Numpy math functions
8. What is Matplotlib?
9. Plotting a function

## What is Numpy?

Numpy (Numerical Python) is a Python library for scientific computation. Numpy is the library that makes Python comparable to Matlab (a very famous scientific computation software). It allows very fast and efficient mathematical computations on vectors, matrices and high-dimensional matrices.

In this course, we will use Numpy extensively therefore, it is a good idea to start tinkering around with it early.

## Prerequisites

In [1]:
import numpy as np
print("hello")

hello


## Creating Numpy arrays

### From lists

You can create a Numpy array from Python lists using `np.array()`

In [ ]:
# Creating a numpy array of elements 1,2,3,4,5
numbers = np.array([1,2,3,4,5])
print(numbers)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


The previous variable `numbers` is of type `np.ndarray` and has some properties. For example:

In [ ]:
print(type(numbers))
print(numbers.dtype)
print(numbers.shape)
print(numbers.ndim)

NameError: ignored

### Using `arange` and `linspace`

Sometimes, you need to create an array with equally-spaced numbers i.e. numbers from 0 to 1 with step 0.01. This can be done with either `np.arange` or `np.linspace`

In [ ]:
# np.arange(start, stop, step)
arr1 = np.arange(0, 1, 0.1) # 1 is not included
print(arr1)

In [ ]:
# np.linspace(start, stop, size)
arr2 = np.linspace(0, 1, 11) # 11 is included
print(arr2)

### Using special functions

There are some special functions to create special vectors and matrices in Numpy. For example, `np.zeros()` will create an array of zeros. `np.ones()` will create an array of ones.

In [ ]:
zeros = np.zeros(10)
print(zeros)

In [ ]:
ones = np.ones(10)
print(ones)

## Indexing and Slicing

Similar to indexing and slicing in normal Python lists, indexing is done using a square brackets after the array name with the index between the two brackets i.e. `numbers[1]`, and slicing is done using a colon between the start and end indices i.e. `numbers[1:3]`.

In [ ]:
print(numbers[1])
print(numbers[1:3])

You can index the last element using the index `-1`. You can also leave the start index empty to indicate the index `0` and the end index empty to indicate the end of the array i.e. `numbers[:3]` will return all elements from the beginning of the array until before element with index `3` - and `numbers[3:]` will return all elements from element of index `3` until the last element in the array.

In [ ]:
print(numbers)
print(numbers[:3])
print(numbers[3:])
print(numbers[:])

### Creating 2-D Matrices

A matrix can be thought of as a number of rows stacked on top of each other. In Python, a matrix can be represented as a list of equal-length lists i.e. `matrix = [[1,2,3],[4,5,6],[7,8,9]]`. This is the same with Numpy. In fact, a matrix in Numpy can be created using `np.array()` as with vectors, but this time with a nested list instead of a normal list between the paranthesis.

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

In [ ]:
# using special functions
zeros = np.zeros((3,3))
print(zeros)

In [ ]:
ones = np.ones((4,4))
print(ones)

`np.diag(list)` will take a list and return a diagonal matrix with the given list as its diagonal. `np.eye(dimension)` will create the identity matrix (a matrix with a diagonal of ones). `np.full(shape, value)` will create a matrix with constant value.

In [ ]:
diag = np.diag([1,2,3,4])
print(diag)

In [ ]:
identity = np.eye(5)
print(identity)

In [ ]:
const = np.full((5,5), 7)
print(const)

### Array shape

Every Numpy array has a property `shape` that returns a tuple indicating the dimension of that array. For example, if `a` is a matrix with 4 rows and 3 columns, then `a.shape` will return `(4,3)`.

In [ ]:
const = np.full((4,3), 2)
print(const)
print(const.shape)

### Indexing and Slicing (again)

Let's assume we have a Numpy array `numbers = np.array([1,2,3])`. Executing the following command `numbers[1]` will return `2`. This is because the element with index `1` is the number `2`. However, let's now assume that the Numpy array `numbers` holds a matrix instead `numbers = np.array([[1,2,3],[4,5,6],[7,8,9]])`, now `numbers[1]` will return `[4,5,6]`. Why? Because `numbers` is a matrix or a collection of rows, the first row has the index `0`, the second has the index `1` and so on, therefore, `number[1]` will return the second element (row) of that matrix.

In [ ]:
numbers = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(numbers)
print(numbers[1])

Now, if we want to select a specific element from the selected row, we use another index, and separate the two indices (the row index and the element's index within the row) with a comma i.e. `numbers[1,2]`. Actually, the `1` is called the row index (or sometimes axis 0) and the `2` is called the column index (or axis 1).

In [ ]:
# return the second row, the third element
print(numbers)
print(numbers[1,2])

What about slicing? In fact, matrix slicing is one of the most brilliant and most used features of Numpy. When slicing, you choose the starting and ending indices in the rows and columns dimensions, and it returns a smaller matrix in the given range.

In [ ]:
# Create a 10x10 identity matrix
numbers = np.identity(10)
print(numbers)

In [ ]:
# get the first 5 rows
print(numbers[0:5,:])

In [ ]:
# get the first 5 columns
print(numbers[:,0:5])

In [ ]:
# get the elements in the first 5 rows and columns
print(numbers[0:5, 0:5])

In [ ]:
# get the elements in the last five rows
print(numbers[5:, :])

## Basic Operations

### Matrix Transpose

In [ ]:
a = np.random.randint(0, 10, (3,6))
print('a:')
print(a)
print('\nTranspose:')
print(a.T)

In [ ]:
a = np.array([1,2,3,4,5])
print(a)
print(a.T)

**Why?** Numpy arrays created from a normal list is called zero-rank array. Its shape is `(n,)` which indicates that it has a single dimension `n`. On the other hand, a vector is either a row vector with shape `(1, n)` or a column vector with shape `(n, 1)`. To create such a vector, we need to add an extra empty axis to tell Numpy that there is now a new dimension added.

In [ ]:
print(a.shape)

In [ ]:
print(a[None, :])
print(a[None, :].shape)

In [ ]:
print(a[:, None])
print(a[:, None].shape)

### Math operations

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

### Multiplication

In [ ]:
print(a * b) # element-wise multiplication
print(a.dot(b)) # dot product
print(a @ b) # the same dot product

## Numpy Math Functions

In [ ]:
a = np.array([1,4,9,16,25])
print(a)

# element-wise
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))
print(np.cos(a))

## What is Matplotlib?

Matplotlib is a Python library for data visualization that produces high-quality figures in any format. Throughout our course, we will try to visualize our 2-D functions to see what is happening and to understand the algorithms better. You should also be able to use Matplotlib to do visualizations yourself.

### Plotting a function

When you first learned to plot a function using a pen and a paper, you drew a table with two rows, the first was for the x-axis values, and the second was for the y-axis values. Each pair of (x,y) axes was then drawn, and finally you connect all the points together using lines to get the final plot.

When using Matplotlib, it is not that different. You begin by creating an array of x-axis values. Then you compute the corresponding y-axis values (using the function you want to plot), then you give the pair of x and y arrays to the `plot()` function to do the rest.

In the next cell, we will plot the `np.sin()` function of x values raning from $[-\pi, \pi]$.

In [ ]:
from matplotlib import pyplot as plt

# Create the x-axis values
x = np.linspace(-np.pi, np.pi, 50)

# Compute the y-axis values
y = np.sin(x)

# Creating a figure
plt.figure()
# Calling the plot function
plt.plot(x, y)
# show the figure
plt.show()

Up till now, this is all you need to know in order to start this course.

**Thank you**.